### ISSUE TITLE
ImportError: cannot import name ScriptMagics

### ISSUE THREAD

**Issue by bluprince13** [santosjorge/cufflinks#74]
I'm not sure what's going wrong here. There seems to be a circular import problem, but I can't figure out what it is. The error occurred with cufflinks 0.11.0.

```
Python 2.7.12 |Anaconda custom (32-bit)| (default, Jun 29 2016, 11:42:13) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import cufflinks
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda2\lib\site-packages\cufflinks\__init__.py", line 14, in <module>
    from . import tools
  File "C:\Anaconda2\lib\site-packages\cufflinks\tools.py", line 5, in <module>
    from .colors import normalize,to_rgba
  File "C:\Anaconda2\lib\site-packages\cufflinks\colors.py", line 12, in <module>
    from IPython.display import HTML,display
  File "C:\Anaconda2\lib\site-packages\IPython\__init__.py", line 49, in <module>
    from .terminal.embed import embed
  File "C:\Anaconda2\lib\site-packages\IPython\terminal\embed.py", line 19, in <module>
    from IPython.terminal.ipapp import load_default_config
  File "C:\Anaconda2\lib\site-packages\IPython\terminal\ipapp.py", line 30, in <module>
    from IPython.core.magics import ScriptMagics
ImportError: cannot import name ScriptMagics
```

**Comment by bluprince13** [comment]
I installed cufflinks 0.12 and the error still persists.

**Comment by bluprince13** [comment]
The error went away after updating ipython from 4.2.0 to 5.3.0.
