### ISSUE TITLE
plotly 3.0 causes warnings

### ISSUE THREAD

**Issue by gideonshalev** [santosjorge/cufflinks#119]
When using the plotly 3.0, the below warnings show up after importing cufflinks.
Would be good to update the code by avoiding the deprecated methods.

```python
/Users/gshalev/.pyenv/versions/3.6.2/lib/python3.6/site-packages/plotly/graph_objs/_deprecations.py:558: DeprecationWarning:

plotly.graph_objs.YAxis is deprecated.
Please replace it with one of the following more specific types
  - plotly.graph_objs.layout.YAxis
  - plotly.graph_objs.layout.scene.YAxis


/Users/gshalev/.pyenv/versions/3.6.2/lib/python3.6/site-packages/plotly/graph_objs/_deprecations.py:531: DeprecationWarning:

plotly.graph_objs.XAxis is deprecated.
Please replace it with one of the following more specific types
  - plotly.graph_objs.layout.XAxis
  - plotly.graph_objs.layout.scene.XAxis
```

**Comment by GIREG-J** [comment]
Hello, 

A quick search into the cufflinks repo yield only two files:
- cufflinks/themes.py
- cufflinks/tools.py

I'm working on a quick PR.

**Comment by ah-** [comment]
Haven't looked into detail, but there might be more fixes required, getting this after a df.iplot():

```
ValueError: 
    Invalid value of type 'builtins.str' received for the 'bgcolor' property of layout.legend
        Received value: 'pearl02'
```

**Comment by taxus13** [comment]
Just to give more feedback:  
When I run
`df.iplot(kind='area',fill=True)`
I get also an ValueError:
`ValueError: 
    Invalid value of type 'builtins.str' received for the 'color' property of layout.legend.font
        Received value: 'grey10'`

**Comment by saeedamen** [comment]
I've had similar issues too with plotly 3.0.0 and cufflinks (fails when I do import cufflinks)

**Comment by GIREG-J** [comment]
@ah- you might be right

After replacing by the go.layout.XAxis and go.layout.YAxis and testing the errors are due to color naming.
Instead of passing the corresponding hex string from the **cnames** dict from _cufflinks/cufflinks/colors.py_, cufflinks passes the color name directly to _plotly.graph_objs.layout.YAxis_, resulting in _ValueError_

Usually _cufflinks.tools_ will convert to RGBA/hex string using the to_rgba function, but since it imports THEMES first, it passes the YAxis/XAxis with invalid colors.

A clunky fix would to convert all the colors in THEMES to its hex string equivalent, but I still don't really know why there is suddenly this problem with colors... 🤔

**Comment by ah-** [comment]
I think it's a new feature, read about it in https://medium.com/@plotlygraphs/introducing-plotly-py-3-0-0-7bb1333f69c6, see "Deep Validation and Helpful Error Messages".

**Comment by kammoh** [comment]
Same ValueError, cufflinks (<=git:master) not usable with plotly 3.0+
Maybe we should open a new issue as this is different from the OP Warning?

**Comment by anotherbugmaster** [comment]
Hello everyone, I think that this change causes the issue:

https://github.com/plotly/plotly.py/blob/master/migration-guide.md#object-array-classes-deprecated

**Comment by DiegoAgher** [comment]
my quick fix was to downgrade to plotly 2.0.0 for the time being

`pip uninstall plotly`
`pip install plotly==2.0.0`

**Comment by GIREG-J** [comment]
@DiegoAgher , Plotly==2.7.0 is working just fine since Plotly uses the  [Semantic Versioning](https://semver.org/) 🙂 (and I tested it)

**Comment by timkpaine** [comment]
Looking a little closer, this is going to be a fairly painful migration.

**Comment by timkpaine** [comment]
getting started on #122

**Comment by santosjorge** [comment]
Yikes. This looks like a painful one. Thank you @timkpaine. Let’s get on it.

**Comment by mlsmall** [comment]
Uninstall version 3.0 and install version 2.7.0. Worked for me.
in anaconda prompt:>  pip install plotly==2.7.0

**Comment by jonmmease** [comment]
Hi all, I just came across this thread. Let me know if you have any questions about migration.

Also, one option that may (or may not) be easier for you would be to replace all of the former graph objects (go.Scatter, etc.) with raw dictionaries\lists and then only build a `go.Figure` object at the very end of the construction process. This would delay validation until the end of the process (after you've replaced the colors etc.) and would be backwards compatible with version 2.7.

**Comment by tdikonda** [comment]
This warning seems to have been resolved in Plotly 3.1.0. Try upgrading to this version and verify.

**Comment by WillDudley** [comment]
Just came across this thread. 

Using Plotly 3.1.0, I had the same value error as ah- commented, however, after upgrading to 3.1.1 I no longer get it.

In both versions, I still get the original warnings described by OP.

**Comment by DavidJBianco** [comment]
Unfortunately, cufflinks 0.13.0 with Plotly 3.1.1 throws the same error:

> /opt/conda/lib/python3.6/site-packages/plotly/graph_objs/_deprecations.py:558: DeprecationWarning:
> 
> plotly.graph_objs.YAxis is deprecated.
> Please replace it with one of the following more specific types
>   - plotly.graph_objs.layout.YAxis
>   - plotly.graph_objs.layout.scene.YAxis
> 
> 
> /opt/conda/lib/python3.6/site-packages/plotly/graph_objs/_deprecations.py:531: DeprecationWarning:
> 
> plotly.graph_objs.XAxis is deprecated.
> Please replace it with one of the following more specific types
>   - plotly.graph_objs.layout.XAxis
>   - plotly.graph_objs.layout.scene.XAxis
>

**Comment by aiguofer** [comment]
I'm having the same issue, although I also get the following error following the warnings when I import cufflinks:

```
  File "/opt/custard/git/adhoc/adhoc/air_metrics.py", line 5, in <module>
    import cufflinks as cf
  File "/home/custard/.local/lib/python2.7/site-packages/cufflinks/__init__.py", line 15, in <module>
    from . import tools
  File "/home/custard/.local/lib/python2.7/site-packages/cufflinks/tools.py", line 37, in <module>
    __LAYOUT_AXIS_X=['xaxis_'+_ for _ in go.XAxis().__dir__()]
AttributeError: 'XAxis' object has no attribute '__dir__'
```

**Comment by santosjorge** [comment]
I've created a plotly3 branch to start testing all the fixes (lot of changes).

**Comment by santosjorge** [comment]
Done. 
**Thank you @timkpaine ** for the help.

**Comment by leirhyh72** [comment]
Hi All,  did this issues solved?  I updated the latest plotly and got the same error again.  What should I do?
Thanks,

Tim

**Comment by timkpaine** [comment]
I am also on latest plotly and it works fine. Can you send a repro and info about your environment (python and plotly/cufflinks versions)

**Comment by leirhyh72** [comment]
Sorry I forget to post the errors which is as follows:
ValueError                                Traceback (most recent call last)
<ipython-input-4-03faaa551155> in <module>()
     21             color = 'colors[i-6]',
     22             opacity = .4,
---> 23             line = dict(width = 0)
     24         ),
     25     ) )

c:\users\leirhyh\appdata\local\programs\python\python37-32\lib\site-packages\plotly\graph_objs\_scattergeo.py in __init__(self, arg, connectgaps, customdata, customdatasrc, fill, fillcolor, geo, hoverinfo, hoverinfosrc, hoverlabel, hovertext, hovertextsrc, ids, idssrc, lat, latsrc, legendgroup, line, locationmode, locations, locationssrc, lon, lonsrc, marker, mode, name, opacity, selected, selectedpoints, showlegend, stream, text, textfont, textposition, textpositionsrc, textsrc, uid, unselected, visible, **kwargs)
   1553         self.lonsrc = lonsrc if lonsrc is not None else _v
   1554         _v = arg.pop('marker', None)
-> 1555         self.marker = marker if marker is not None else _v
   1556         _v = arg.pop('mode', None)
   1557         self.mode = mode if mode is not None else _v

c:\users\leirhyh\appdata\local\programs\python\python37-32\lib\site-packages\plotly\basedatatypes.py in __setattr__(self, prop, value)
   2702                 prop in self._validators):
   2703             # Let known properties and private properties through
-> 2704             super(BasePlotlyType, self).__setattr__(prop, value)
   2705         else:
   2706             # Raise error on unknown public properties

c:\users\leirhyh\appdata\local\programs\python\python37-32\lib\site-packages\plotly\graph_objs\_scattergeo.py in marker(self, val)
    693     @marker.setter
    694     def marker(self, val):
--> 695         self['marker'] = val
    696 
    697     # mode

c:\users\leirhyh\appdata\local\programs\python\python37-32\lib\site-packages\plotly\basedatatypes.py in __setitem__(self, prop, value)
   2665             # ### Handle compound property ###
   2666             if isinstance(validator, CompoundValidator):
-> 2667                 self._set_compound_prop(prop, value)
   2668 
   2669             # ### Handle compound array property ###

c:\users\leirhyh\appdata\local\programs\python\python37-32\lib\site-packages\plotly\basedatatypes.py in _set_compound_prop(self, prop, val)
   2963         validator = self._validators.get(prop)
   2964         # type: BasePlotlyType
-> 2965         val = validator.validate_coerce(val)
   2966 
   2967         # Save deep copies of current and new states

c:\users\leirhyh\appdata\local\programs\python\python37-32\lib\site-packages\_plotly_utils\basevalidators.py in validate_coerce(self, v)
   1875 
   1876         elif isinstance(v, dict):
-> 1877             v = self.data_class(**v)
   1878 
   1879         elif isinstance(v, self.data_class):

c:\users\leirhyh\appdata\local\programs\python\python37-32\lib\site-packages\plotly\graph_objs\scattergeo\_marker.py in __init__(self, arg, autocolorscale, cauto, cmax, cmin, color, colorbar, colorscale, colorsrc, gradient, line, opacity, opacitysrc, reversescale, showscale, size, sizemin, sizemode, sizeref, sizesrc, symbol, symbolsrc, **kwargs)
   1175         self.cmin = cmin if cmin is not None else _v
   1176         _v = arg.pop('color', None)
-> 1177         self.color = color if color is not None else _v
   1178         _v = arg.pop('colorbar', None)
   1179         self.colorbar = colorbar if colorbar is not None else _v

c:\users\leirhyh\appdata\local\programs\python\python37-32\lib\site-packages\plotly\basedatatypes.py in __setattr__(self, prop, value)
   2702                 prop in self._validators):
   2703             # Let known properties and private properties through
-> 2704             super(BasePlotlyType, self).__setattr__(prop, value)
   2705         else:
   2706             # Raise error on unknown public properties

c:\users\leirhyh\appdata\local\programs\python\python37-32\lib\site-packages\plotly\graph_objs\scattergeo\_marker.py in color(self, val)
    165     @color.setter
    166     def color(self, val):
--> 167         self['color'] = val
    168 
    169     # colorbar

c:\users\leirhyh\appdata\local\programs\python\python37-32\lib\site-packages\plotly\basedatatypes.py in __setitem__(self, prop, value)
   2674             # ### Handle simple property ###
   2675             else:
-> 2676                 self._set_prop(prop, value)
   2677 
   2678         # Handle non-scalar case

c:\users\leirhyh\appdata\local\programs\python\python37-32\lib\site-packages\plotly\basedatatypes.py in _set_prop(self, prop, val)
   2904         # ------------
   2905         validator = self._validators.get(prop)
-> 2906         val = validator.validate_coerce(val)
   2907 
   2908         # val is None

c:\users\leirhyh\appdata\local\programs\python\python37-32\lib\site-packages\_plotly_utils\basevalidators.py in validate_coerce(self, v, should_raise)
   1077             validated_v = self.vc_scalar(v)
   1078             if validated_v is None and should_raise:
-> 1079                 self.raise_invalid_val(v)
   1080 
   1081             v = validated_v

c:\users\leirhyh\appdata\local\programs\python\python37-32\lib\site-packages\_plotly_utils\basevalidators.py in raise_invalid_val(self, v)
    223             typ=type_str(v),
    224             v=repr(v),
--> 225             valid_clr_desc=self.description()))
    226 
    227     def raise_invalid_elements(self, invalid_els):

ValueError: 
    Invalid value of type 'builtins.str' received for the 'color' property of scattergeo.marker
        Received value: 'colors[i-6]'

    The 'color' property is a color and may be specified as:
      - A hex string (e.g. '#ff0000')
      - An rgb/rgba string (e.g. 'rgb(255,0,0)')
      - An hsl/hsla string (e.g. 'hsl(0,100%,50%)')
      - An hsv/hsva string (e.g. 'hsv(0,100%,100%)')
      - A named CSS color:
            aliceblue, antiquewhite, aqua, aquamarine, azure,
            beige, bisque, black, blanchedalmond, blue,
            blueviolet, brown, burlywood, cadetblue,
            chartreuse, chocolate, coral, cornflowerblue,
            cornsilk, crimson, cyan, darkblue, darkcyan,
            darkgoldenrod, darkgray, darkgrey, darkgreen,
            darkkhaki, darkmagenta, darkolivegreen, darkorange,
            darkorchid, darkred, darksalmon, darkseagreen,
            darkslateblue, darkslategray, darkslategrey,
            darkturquoise, darkviolet, deeppink, deepskyblue,
            dimgray, dimgrey, dodgerblue, firebrick,
            floralwhite, forestgreen, fuchsia, gainsboro,
            ghostwhite, gold, goldenrod, gray, grey, green,
            greenyellow, honeydew, hotpink, indianred, indigo,
            ivory, khaki, lavender, lavenderblush, lawngreen,
            lemonchiffon, lightblue, lightcoral, lightcyan,
            lightgoldenrodyellow, lightgray, lightgrey,
            lightgreen, lightpink, lightsalmon, lightseagreen,
            lightskyblue, lightslategray, lightslategrey,
            lightsteelblue, lightyellow, lime, limegreen,
            linen, magenta, maroon, mediumaquamarine,
            mediumblue, mediumorchid, mediumpurple,
            mediumseagreen, mediumslateblue, mediumspringgreen,
            mediumturquoise, mediumvioletred, midnightblue,
            mintcream, mistyrose, moccasin, navajowhite, navy,
            oldlace, olive, olivedrab, orange, orangered,
            orchid, palegoldenrod, palegreen, paleturquoise,
            palevioletred, papayawhip, peachpuff, peru, pink,
            plum, powderblue, purple, red, rosybrown,
            royalblue, saddlebrown, salmon, sandybrown,
            seagreen, seashell, sienna, silver, skyblue,
            slateblue, slategray, slategrey, snow, springgreen,
            steelblue, tan, teal, thistle, tomato, turquoise,
            violet, wheat, white, whitesmoke, yellow,
            yellowgreen
      - A number that will be interpreted as a color
        according to scattergeo.marker.colorscale
      - A list or array of any of the above

**Comment by leirhyh72** [comment]
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)] on win32
import plotly
plotly.__version__
'3.2.0'

import cufflinks
cufflinks.__version__
'0.13.0'

**Comment by leirhyh72** [comment]
Thanks and I appreciate your time.
Tim

**Comment by coulanuk** [comment]
I get the same error with the same versions as @timkpaine .

Error : 
ValueError:  Invalid value of type 'builtins.str' received for the 'bgcolor' property of layout.legend
        Received value: 'pearl02'

O/S : Ubuntu 18.04
Python Version: 3.7.0 (default, Jun 28 2018, 19:31:47) 
[GCC 7.3.0]
Plotly Version: 3.2.0
Cufflinks Version: 0.13.0

**Repro (taken from the [online example:](https://plot.ly/python/offline/))**
import plotly
import cufflinks as cf
import sys
cf.set_config_file(offline=True)
print("Python Version: %s" % sys.version)
print("Plotly Version: %s" % plotly.__version__)
print("Cufflinks Version: %s" % cf.__version__)
iplot(cf.datagen.lines().iplot(asFigure=True,kind='scatter',xTitle='Dates',yTitle='Returns',title='Returns'))

Many thanks & appreciate your great efforts.

Andy

**Comment by timkpaine** [comment]
I can repro against pypi disted cufflinks, but not my source repo (which matches this repo). Can you try to pip install this git repo directly and see if it still happens?

<img width="794" alt="screen shot 2018-09-11 at 4 01 32 pm" src="https://user-images.githubusercontent.com/3105306/45384403-fa80a400-b5db-11e8-82f3-c0cb31559d0d.png">

**Comment by timkpaine** [comment]
yeah, what got disted is not whats on master, for sure

**Comment by leirhyh72** [comment]
my code is ad following:
import plotly
import plotly.plotly as py
import plotly.graph_objs as go

plotly.offline.init_notebook_mode()

import pandas as pd
coords = pd.concat([housing['latitude'], housing['longitude'], housing['population']], axis=1)

coords = coords.sample(frac=0.1, replace=True)
cases = []
colors = ['rgb(239,243,255)','rgb(189,215,231)','rgb(107,174,214)','rgb(33,113,181)']
months = {6:'June',7:'July',8:'Aug',9:'Sept'}

for i in range(6,10)[::-1]:
    cases.append(go.Scattergeo(
        lon = coords['longitude'],
        lat = coords['latitude'],
        marker = dict(
            size = coords['population']/1000,
            color = 'colors[i-6]',
            opacity = .4,
            line = dict(width = 0)
        ),
    ) )

cases[0]['mode'] = 'markers'

layout = go.Layout(
    title = 'Hey look! It\'s a scatter plot on a map!',
    geo = dict(
        resolution = 100,
        scope = 'usa',
        showframe = False,
        showcoastlines = True,
        showland = True,
        landcolor = "rgb(229, 229, 229)",
        countrycolor = "rgb(255, 255, 255)" ,
        coastlinecolor = "rgb(255, 255, 255)",
        projection = dict(
            type = 'Mercator'
        ),
        lonaxis = dict( range= [ -124.0, -113.0 ] ),
        lataxis = dict( range= [ 32.0, 43.0 ] ),
        
    ),
    legend = dict(
           traceorder = 'reversed'
    )
)


fig = go.Figure(layout=layout, data=cases)
plotly.offline.iplot(fig, validate=False, filename='iantest')

**Comment by timkpaine** [comment]
@leirhyh72 please install 0.14

**Comment by leirhyh72** [comment]
when I use pip install, it is 0.14,  do I need  to install from the source??

**Comment by leirhyh72** [comment]
I mean 0.13, sorry

**Comment by timkpaine** [comment]
0.14 isn't disted to pypi yet:
```pip install git+git://github.com/santosjorge/cufflinks.git#egg=cufflinks```

**Comment by leirhyh72** [comment]
Do I need to uninstall the 0.13 and try to install from source?  Thanks

**Comment by timkpaine** [comment]
read above

**Comment by leirhyh72** [comment]
I did use "pip install git+git://github.com/santosjorge/cufflinks.git#egg=cufflinks"
but the version is still 0.13.  Don't know why.  I may uninstall all cufflinks if possible and reinstall it again.  What do you think?  Thanks, Tim

**Comment by timkpaine** [comment]
did it actually install? if you have an install you probably need -U

**Comment by leirhyh72** [comment]
Hi Tim, after I add -U, 0.14 was successfully installed.  However, the same error appeared.  Don't know why.  Any input?  Thanks,  Tim

**Comment by kenibrewer** [comment]
@leirhyh72 Are you using cufflinks within an iPython session or a Jupyter Notebook? You may need to restart your kernel to get it to work. I continued having the same error as you after install until I restarted my Jupyter notebook kernel.

**Comment by AlaaElagha** [comment]
Upgrading to 0.14.0 with
pip install git+git://github.com/santosjorge/cufflinks.git#egg=cufflinks -U
works. I am running Jupyter notebook on OSX.

I have struggled with this for the last couple of week. Thank you so much guys

import plotly
plotly.__version__
'3.2.0'

import cufflinks
cufflinks.__version__
'0.14.1'

**Comment by DavidJBianco** [comment]
I can confirm that this is now working properly for me with Plotly 3.2.1 and cufflinks 0.14.4. Thanks for all the hard work @santosjorge!  Not to bug you too much about it, but do you have plans to push this to PyPi soon?

**Comment by taxus13** [comment]
@DavidJBianco when did you check for cufflinks 0.14.4? 
It is listed at PyPi: https://pypi.org/project/cufflinks/

**Comment by DavidJBianco** [comment]
Sorry, you're correct. I had it installed from conda-forge, which isn't up-to-date.  Switching to the PyPi version was pretty simple.

**Comment by cpoptic** [comment]
Can confirm this error still is thrown under Plotly version 3.9.0   and cufflinks version 0.15.

How do we resolve this? (aside from downgrading from Plotly 3.9.0)

**Comment by Idodox** [comment]
@cpoptic did you install from conda? the cufflinks version there is 0.13, where the current version is 0.15. Support for plotly 3.0 was added in version 0.14

check your version (cf.__version__)

upgrade using pip: pip install cufflinks --upgrade

**Comment by Idodox** [comment]
@cpoptic are you certain you're running 0.15? I was running 0.13 when I hit it and upgrading certainly solved it for me..

**Comment by Jvdahemad** [comment]
Same error with plotly 3.9, but downgrading it to 3.7 does help.

**Comment by discdiver** [comment]
3.9 with 0.13 was problematic for me. Upgrading cufflinks to 0.15 fixed the issue. FYI, the latest version on Conda is 0.13.

**Comment by santosjorge** [comment]
At the moment there is no official Conda repo. I think someone created one but not sure if it is being kept up to date. Better to always use PyPi.
